[tool.poetry]
name = "translate-whisper-x"
version = "0.1.0"
description = ""
authors = ["dima"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
av = "^15.1.0"
whisperx = "^3.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
